modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/thrasosc/soulscraft-core-mod/issues"
license = "GNU GPL 3.0"

[[mods]]
modId = "soulscraft"
version = "${version}"
displayName = "SoulsCraft"
authors = "Pixel Dream Studios, thrasosc, banditbytes, veroxuniverse, alshanex"
description = '''
Core Mod for the SoulsCraft Series of Mods
'''
#logoFile = ""

[[dependencies.soulscraft]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.soulscraft]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.soulscraft]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.soulscraft]]
modId = "azurelib"
type = "required"
versionRange = "[2.3.28,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "soulscraft.mixins.json"
